### PR TITLE
Added raw tags to the chat html pages so the template will function

### PR DESCRIPTION
**Pull request by notzippy**
Added raw tags to the chat html pages so the template will function
Updated travis

Fixes this issue
https://github.com/revel/revel/issues/1128
https://github.com/revel/examples/issues/15

### CODE REVIEW

**Comment by shawncatz** [comment]
@notzippy is this good to be merged?

**Comment by pedromorgan** [comment]
I'm not sure about this at all... 

Seems silly and daft..

can anyone explain <% in firt place or am i missing something

**Comment by notzippy** [comment]
It is good to be merged, the script is valid JavaScript templates.

**Comment by pedromorgan** [comment]
Ok javascript  templates.. ok. .why my hairs stand on end as a dog to a statically chared cat..

**Pull request merged**
