### PR TITLE
Upgrade dependencies for revel framework to 1.0.x in go.mod; fixes 

### PR DESCRIPTION
**Pull request by obsti8383**
This fixes compile errors for the booking app, that occur, if you compile current version from master.
closes #59

### CODE REVIEW

**Comment by z9r5** [comment]
@notzippy Hello! Please review this PR as the booking app is not working now.

Thanks.

**Comment by notzippy** [comment]
Can you drop the `go.sum` file it was committed by accident and is not needed.

**Comment by obsti8383** [comment]
> Can you drop the `go.sum` file it was committed by accident and is not needed.

@notzippy done.

**Review by efraimowen — APPROVED** [review]

**Comment by notzippy** [comment]
thanks @obsti8383

**Pull request merged**
